### ISSUE TITLE
loadtxt compat: empty `comments`

### ISSUE THREAD

**Issue by rossbar** [BIDS-numpy/npreadtext#14]
Just a minor compatibility note:

`npreadtxt` seems to treat empty comment strings (`comments=""`) like `comments=None`, whereas `np.loadtxt` raises an exception:

```python
>>> from npreadtxt import _loadtxt
>>> import io
>>> import numpy as np
>>> s = StringIO("1 2 3")
>>> _loadtxt(s, comments="")
array([1., 2., 3.])
>>> s.seek(0)
>>> np.loadtxt(s, comments="")
Traceback (most recent call last)
   ...
ValueError: empty separator
```

IMO `npreadtxt`'s behavior is more sensible, but it is an incompatibility so adding it to the issue tracker just so it's not lost.

**Comment by seberg** [comment]
This one is nice:
```
In [24]: np.loadtxt(StringIO("1\n2"), dtype="S100", comments=[""])
<ipython-input-24-5a394dc7cbe0>:1: UserWarning: loadtxt: Empty input file: "<_io.StringIO object at 0x7fa425ed33a0>"
  np.loadtxt(StringIO("1\n2"), dtype="S100", comments=[""])
Out[24]: array([], dtype='|S100')
```
but it doesn't really matter :).  And it actually changed to error in current NumPy main...

**Comment by seberg** [comment]
Lets add a deprecation for this: To disable comments, the user should use `comments=None` and not `comments=""`.

**Comment by seberg** [comment]
```
In [3]: np.loadtxt(['1 "\n1"', "2 2"], comments="")
<ipython-input-3-9841b64304b5>:1: UserWarning: loadtxt: Empty input file: "['1 "\n1"', '2 2']"
  np.loadtxt(['1 "\n1"', "2 2"], comments="")
Out[3]: array([], dtype=float64)
```
?!

**Comment by seberg** [comment]
Hahaha, looks like NumPy 1.21.x broke `comments=""` to just comment out literally everything..

**Comment by seberg** [comment]
OK. since `comments=""` seems to have been broken until NumPy 1.22 (and now gives an error), it seems good to just disable it.

Further passing an empty string for `delimiter` or `quote` should be an error now.  The only weird thing is that `delimiter=None` means "any whitespace" while `quote=None`, and `comments=None` means that there is no quote/comment character.

**Comment by seberg** [comment]
an empty comment now raises a nice ValueError as per Ross' addition.
