### ISSUE TITLE
BUG: Loadtxt and encodings of control characters

### ISSUE THREAD

**Issue by seberg** [BIDS-numpy/npreadtext#43]
The current loadtxt typically encodes all special characters (comments, delimiter, etc.) if the input is bytes.  The initial wrappers only did this for comment and `latin1`.
We probably just get away with it, because it is practically always just ascii anyway.

We need some good test coverage for byte strings in the `loadtxt` wrapper.  And ensure we reject them in the "new" interace.

**Comment by seberg** [comment]
I think I fixed this up in the last small changes (for loadtxt).  But still needs some tests.

**Comment by rossbar** [comment]
The test added in numpy/numpy@bab8610 should be sufficient to close this.
